---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  namespace: cst8918
  labels:
    app: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app-container
          image: <IMAGE_PLACEHOLDER>
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather
                  key: api-key
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: weather
                  key: redis-host
            - name: REDIS_PORT
              value: "6379"