name: Build and Push Remix App

on:
  pull_request:
    branches:
      - main
    paths:
      - 'application/**'
  push:
    branches:
      - main
    paths:
      - 'application/**'

permissions:
  contents: read
  id-token: write

jobs:
  docker-build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    env:
      ACR_NAME: ${{ vars.ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   subscription-id: "45877b2c-82aa-41e4-8da1-8a4ebb66eaad"

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Docker Build
        run: |
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} ./application
          docker tag $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

      - name: Docker Push
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest